[package]
name = "obsidian-ls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
once_cell = "1.18.0"
rayon = "1.7.0"
regex = "1.10.2"
tree-sitter = "0.20.10"
tree-sitter-md = "0.1.5"
