[package]
name = "obsidian-ls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.29"
itertools = "0.10.5"
once_cell = "1.18.0"
pathdiff = "0.2.1"
rayon = "1.7.0"
regex = "1.10.2"
ropey = "1.6.1"
tokio = { version="1.34.0", features=["full"]}
tower-lsp = "0.20.0"
tree-sitter = "0.20.10"
tree-sitter-md = "0.1.5"
